### ISSUE TITLE
support for multiprocess / shared memory

### ISSUE THREAD

**Issue by hayguen** [df308/x9#10]
slightly similar to the _custom allocator issue_ https://github.com/df308/x9/issues/5 - but still different:
it would be great, if user could optionally pass the memory pointer (of a shared memory) to use explicitly to some of the functions like `x9_create_inbox()`

not sure, but would hope, that this would support interprocess communication

**Comment by df308** [comment]
Hi!

Yes - In v2.0 that feature will be available. (I plan to release next month - see the README.md)
X9 will be both multithreading and multiprocessing capable using the same write/read functions.

DF
