### ISSUE TITLE
Question/enhancement: in x9_inbox_internal struct, perhaps you can allocate name as a flexible array member? 

### ISSUE THREAD

**Issue by mykaul** [df308/x9#6]
Currently there are 32 bytes used: 8 for the 'name' pointer and 24 for padding. Instead, perhaps you can define name as [], allocate it (inc. padding for alignment) as part of the allocation of x9_inbox_internal?
You'll save an allocation/de-allocation call, few bytes, but more importantly, they'll be close to each other (so name is not a pointer away to when you access it).

**Comment by mykaul** [comment]
Same for node->inboxes[] ?

**Comment by df308** [comment]
Hi.

It would conflict with x9_node.

See [here](https://wiki.sei.cmu.edu/confluence/display/c/DCL38-C.+Use+the+correct+syntax+when+declaring+a+flexible+array+member)
```
Structures with a flexible array member can be used to produce code with defined behavior.  
However, some restrictions apply:

1. The incomplete array type must be the last element within the structure.
2. There cannot be an array of structures that contain a flexible array member.
3. Structures that contain a flexible array member cannot be used as a member of another structure.
4. The structure must contain at least one named member in addition to the flexible array member.
```

DF
